const menuItems = [
  {
    id: 1,
    name: "Alder Grilled Chinook Salmon",
    description: 'Tosted french bread topped with romano & cheddar',
    calories: 550,
    type: 'starter',
    price: 32
  },
  {
    id: 2,
    name: "Chocolate Brownie Sundae",
    description: "Warm chocolate brownie topped with vanilla ice cream and hot fudge",
    calories: 500,
    type: "drinks",
    price: 10,
  },
  {
    id: 3,
    name: "Berries and creme tart",
    description: 'Tosted french bread topped with romano & cheddar',
    calories: 550,
    type: 'starter',
    price: 32
  },
  {
    id: 4,
    name: "Margherita Pizza",
    description: "Traditional Italian pizza with fresh tomatoes, mozzarella, and basil",
    calories: 700,
    type: "main",
    price: 14,
  },
  {
    id: 5,
    name: "Chicken Alfredo Pasta",
    description: "Creamy pasta with grilled chicken and Parmesan cheese",
    calories: 800,
    type: "main",
    price: 18,
  },
  {
    id: 6,
    name: "Classic Cheeseburger",
    description: "Juicy beef patty with melted cheese, lettuce, and tomato",
    calories: 600,
    type: "main",
    price: 15,
  },
  {
    id: 7,
    name: "Fresh Fruit Smoothie",
    description: "Blend of fresh fruits, yogurt, and honey",
    calories: 200,
    type: "drinks",
    price: 6,
  },
  {
    id: 8,
    name: "Cheese and Bacon Stuffed Mushrooms",
    description: "Mushroom caps filled with cream cheese and bacon",
    calories: 350,
    type: "main",
    price: 9,
  },
  {
    id: 9,
    name: "Pesto Pasta",
    description: "Pasta tossed in homemade pesto sauce with pine nuts and Parmesan cheese",
    calories: 600,
    type: "starter",
    price: 16,
  },
  {
    id: 10,
    name: "Tiramisu",
    description: "Italian coffee-flavored dessert made with ladyfingers and mascarpone cheese",
    calories: 450,
    type: "drinks",
    price: 10,
  },
  {
    id: 11,
    name: "Caprese Salad",
    description: "Fresh tomatoes, mozzarella cheese, basil, and balsamic glaze",
    calories: 250,
    type: "dessert",
    price: 11,
  },
  {
    id: 12,
    name: "Sushi Roll Combo",
    description: "Assorted sushi rolls with soy sauce and wasabi",
    calories: 400,
    type: "dessert",
    price: 20,
  },
  {
    id: 13,
    name: "Mango Lassi",
    description: "Traditional Indian yogurt-based drink with mango puree",
    calories: 180,
    type: "drinks",
    price: 7,
  },
  {
    id: 14,
    name: "Spinach and Feta Stuffed Chicken",
    description: "Chicken breast filled with spinach, feta cheese, and herbs",
    calories: 450,
    type: "dessert",
    price: 17,
  },
  {
    id: 15,
    name: "Key Lime Pie",
    description: "Tangy and creamy pie with a graham cracker crust",
    calories: 320,
    type: "dessert",
    price: 9,
  },
  {
    id: 16,
    name: "Mushroom Risotto",
    description: "Creamy risotto with sautéed mushrooms and Parmesan cheese",
    calories: 400,
    type: "starter",
    price: 16,
  }
]


const shopItems = [
  {
    id:1,
    name: 'Fresh Lime',
    price: 23,
    img: 'https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 4,
    quantity: 5,   
  },
  {
    id:2,
    name: 'Chocolate Muffin',
    price: 32,
    img: 'https://images.pexels.com/photos/5150202/pexels-photo-5150202.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 5,
    quantity: 5,   
  },
  {
    id:3,
    name: 'Burger',
    price: 20,
    img: 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 3,
    quantity: 5,   
  },
  {
    id:4,
    name: 'Country Burger',
    price: 21,
    img: 'https://images.pexels.com/photos/327158/pexels-photo-327158.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 5,
    quantity: 5,   
  },
  {
    id: 5,
    name: 'Pizza',
    price: 29,
    img: 'https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 4,
    quantity: 5,   
  },
  {
    id:6,
    name: 'Sandwiches',
    price: 35,
    img: 'https://images.pexels.com/photos/1633559/pexels-photo-1633559.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 4,
    quantity: 5,   
  },
  {
    id:7,
    name: 'Chicken Chup',
    price: 40,
    img: 'https://images.pexels.com/photos/12842989/pexels-photo-12842989.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 5,
    quantity: 5,   
  },
  {
    id:8,
    name: 'Spaghetti',
    price: 42,
    img: 'https://images.pexels.com/photos/1527603/pexels-photo-1527603.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 3,
    quantity: 5,   
  },
  {
    id:9,
    name: 'French fries',
    price: 33,
    img: 'https://images.pexels.com/photos/1651166/pexels-photo-1651166.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 3,
    quantity: 5,   
  },
  {
    id:10,
    name: 'Donut',
    price: 26,
    img: 'https://images.pexels.com/photos/2955820/pexels-photo-2955820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 4,
    quantity: 5,   
  },
  {
    id:11,
    name: 'Italiano Coffe',
    price: 24,
    img: 'https://images.pexels.com/photos/3020919/pexels-photo-3020919.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 5,
    quantity: 5,   
  },
  {
    id:12,
    name: 'Salmon',
    price: 48,
    img: 'https://images.pexels.com/photos/1516415/pexels-photo-1516415.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 4,
    quantity: 5,   
  },
  {
    id:13,
    name: 'Bean stew',
    price: 52,
    img: 'https://images.pexels.com/photos/128408/pexels-photo-128408.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 4,
    quantity: 5,   
  },
  {
    id:14,
    name: 'Grilled fish',
    price: 18,
    img: 'https://images.pexels.com/photos/842142/pexels-photo-842142.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 4,
    quantity: 5,   
  }, 
  {
    id:15,
    name: 'French toast',
    price: 26,
    img: 'https://images.pexels.com/photos/11577595/pexels-photo-11577595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 15,
    quantity: 5,   
  } 
]

export {menuItems, shopItems}